apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: initbot-frontend
  namespace: default
spec:
  secretName: initbot-frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: initbot.krishdev.xyz
  dnsNames:
  - initbot.krishdev.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: initbot-backend
  namespace: default
spec:
  secretName: initbot-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.initbot.krishdev.xyz
  dnsNames:
  - api.initbot.krishdev.xyz
---